name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync files to S3
      run: |
        aws s3 cp frontend/projects.json s3://vccodelabs/projects.json --only-show-errors
        aws s3 cp frontend/styles.css s3://vccodelabs/styles.css --only-show-errors
        aws s3 cp frontend/index.html s3://vccodelabs/index.html --only-show-errors
        
